// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1WIuo8C2GZG1jpA4Et18zt1RngfmE7o',
    appId: '1:977582741172:web:cb1f6c133a714d5f2169e1',
    messagingSenderId: '977582741172',
    projectId: 'crud-d6654',
    authDomain: 'crud-d6654.firebaseapp.com',
    storageBucket: 'crud-d6654.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAs5EHJ--xK6SIMZpV-Fbj5YCH5ynXUrg',
    appId: '1:977582741172:android:19642bad42680b712169e1',
    messagingSenderId: '977582741172',
    projectId: 'crud-d6654',
    storageBucket: 'crud-d6654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpp3aOy9js2iA-jcxEEVKqwVhmLKe_9c',
    appId: '1:977582741172:ios:ce835a702586e60b2169e1',
    messagingSenderId: '977582741172',
    projectId: 'crud-d6654',
    storageBucket: 'crud-d6654.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUpp3aOy9js2iA-jcxEEVKqwVhmLKe_9c',
    appId: '1:977582741172:ios:ce835a702586e60b2169e1',
    messagingSenderId: '977582741172',
    projectId: 'crud-d6654',
    storageBucket: 'crud-d6654.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm1WIuo8C2GZG1jpA4Et18zt1RngfmE7o',
    appId: '1:977582741172:web:d8ab07bb1ed24df22169e1',
    messagingSenderId: '977582741172',
    projectId: 'crud-d6654',
    authDomain: 'crud-d6654.firebaseapp.com',
    storageBucket: 'crud-d6654.firebasestorage.app',
  );
}
